### ISSUE TITLE
Confusion about checkpoints

### ISSUE THREAD

**Issue by Kyrie-LiuX** [sail-sg/CLoT#10]
How to solve this problem,just download the Qwen-VL-chat checkpoints and merge it with CLoT_cn into a folder?
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Qwen/Qwen-VL-Chat is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by zhongshsh** [comment]
The error is caused by the network issue when trying to download `Qwen/Qwen-VL-Chat` from Hugging Face. You can try to download it from [ModelScope](https://modelscope.cn/models/qwen/Qwen-VL-Chat/summary).
