### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by bingnoi** [sail-sg/CLoT#16]
fail to load the gradio page, any suggestion?

**Comment by bingnoi** [comment]
turn to python inference, it responds nothing

**Comment by dedekinds** [comment]
See this similar issue https://github.com/sail-sg/CLoT/issues/7. Did you use Linux or Windows? It seems there are some unknown errors while using Windows.

**Comment by bingnoi** [comment]
i use linux actually

**Comment by dedekinds** [comment]
Can you provide me with more details of your error information? e.g. the error info screenshot etc.

**Comment by bingnoi** [comment]
我直接用中文给你说吧，我用的是一台24g的3090，权重我已经下载在本地了，运行gradio无异常报错，但是网页是空的，点f12 ，console输出Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH 这个错误，然后我用的inference跑，代码也没有报错，但是输出是空的

**Comment by bingnoi** [comment]
补充一点信息 因为你的qwen权重是写的huggingface地址 我把这个地址改成我的本地地址了 除此以外无改动

**Comment by bingnoi** [comment]
close, the reason is the network failure
