### ISSUE TITLE
not so funny

### ISSUE THREAD

**Issue by imfinethanks** [sail-sg/CLoT#7]
![20240411-220107](https://github.com/sail-sg/CLoT/assets/36071470/2c444590-01b5-4734-9998-4416a4e301de)

A.
B.you
C.need
D.1
E.2
F.ah

请问这个结果正常吗？看起来并不是很搞笑

**Comment by zhongshsh** [comment]
Your generated content is **not a complete sentence**. I suspect there might be an issue with your generation config. You may need to check `generation_config.json` (in checkpoint dir), especially if `max_new_tokens` in the config is mistakenly set to 1.

My generation during testing is normal. (See attached image, I find this response quite interesting, no offense intended).

![17129093679981](https://github.com/sail-sg/CLoT/assets/62104945/ce8a9007-48d5-4e51-ac72-b85f2a87c1e8)

**Comment by imfinethanks** [comment]
max_new_tokens=512没发现问题，不过环境从windows+pytorch2.2切换成ubuntu+pytorch2.0后正常了。
![微信图片_20240412220939](https://github.com/sail-sg/CLoT/assets/36071470/e63db2e0-083f-44c4-81cd-8e7138e3d8c4)
Awesome
